FROM debian:bullseye-slim

RUN apt-get update -y

RUN apt-get install -y python3

RUN apt-get -y install python3-pip

COPY requirements.txt /

RUN pip3 install -r requirements.txt

CMD ["bash"]
